apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ambassador
resources:
  - namespace.yaml
  - helmrepository-telepresence.yaml
  - helmrelease-telepresence.yaml
configMapGenerator:
  - name: traffic-manager-values
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true
