apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease-telepresence.yaml
configMapGenerator:
  - name: traffic-manager-values
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true
